### ISSUE TITLE
Scarface fix

### ISSUE THREAD

**Issue by Invictaz** [kozarovv/PS2-Configs#1]
Do you have a fix for Scarface?

**Comment by kozarovv** [comment]
For now there is no fix for Scarface. I know the issue, and what causing it. But i can't fix it for now.

**Comment by Invictaz** [comment]
@kozarovv 

What is the issue and what is causing it?

**Comment by kozarovv** [comment]
Some code is constantly recompiled what cause massive resources usage. In pcsx2 it is resolved by use hack in emu code. In ps4 we need to find out which parts of code are problematic, then use lua function to keep them precompiled to avoid recompilation with every program cycle. 

Code for it will look similar to this, but with different addresses: 

`require("utils")
local eeObj = getEEObject()
local PrecompileAddrs = Queue.new(
   {
	0x3b92ec,
	0x1f23d0,
	0x2bad48,
	0x2b9718,
	0x14d6c4,
	0x14d7fc,
	0x1b5a44,
	0x14fbf4,
	0x1b7aac,
	0x195e38,
	0x14f4f4,
})
`
And will include maaaany more memory addresses. For now is basically impossible to do, but maybe someday.

**Comment by Invictaz** [comment]
Is this also the same on PS3?

**Comment by kozarovv** [comment]
Yes problem is the same, but no idea how to fix it on ps3.

**Comment by Vitt0xLar** [comment]
require("utils") local eeObj = getEEObject() local PrecompileAddrs = Queue.new

i' ve tried this code with my memory addresses but it freeze on pic1 .
What can i do ?

**Comment by Vitt0xLar** [comment]
[Scarface The World Is Yours Addresses.txt](https://github.com/kozarovv/PS2-Configs/files/2318973/Scarface.The.World.Is.Yours.Addresses.txt)

This contains 100 memory addresses maybe this could help ?

**Comment by Invictaz** [comment]
@kozarovv Any update on this?

**Comment by Thibobo** [comment]
on PS3 CECH A (full hardware emu) this appears to work fine according to some people

on my PS3 CECH C04 (partial hw, partial sw emu) it works, but lags heavily

on my ps3 slim with only SW emu, it lags as hard as my CECH C04

@kozarovv you can always contact me on twitter or discord to test new configs

**Comment by kozarovv** [comment]
Hello everyone :) No, sadly i no longer own hackable PS4. So i did nothing since very long time. Actually that's why this repository don't get any updates. 

About PS3 emu, Scarface can be fixed. But my knowledge is limited, i can't do this. At least for now. 
PS4 fix require really simple fix, but i don't know correct address. PS3 fix probably require rewriting part of function.

**Comment by Vitt0xLar** [comment]
> Hello everyone :) No, sadly i no longer own hackable PS4. So i did nothing since very long time. Actually that's why this repository don't get any updates.
> 
> About PS3 emu, Scarface can be fixed. But my knowledge is limited, i can't do this. At least for now.
> PS4 fix require really simple fix, but i don't know correct address. PS3 fix probably require rewriting part of function.

Hi kozarow, as we know this game has two problems on Ps4:
1) microVU1 costant recompilation
2)Flickering textures
I wrote you last summer, and now i want let you know that the first problem has been fixed in PCSX2, they clamped from 0x7fffffff to 0x80000000 for more information see this code:
https://github.com/PCSX2/pcsx2/blob/master/pcsx2/x86/microVU_Compile.inl
So the correct addresses must be those, but in order to precompile all theese addresses i need to copy one by one in PCSX2 debugger and i don't know if there are better tools, but for flickering textures i don't know ho to fix them.
Name of gamefix in PCSX2 : ScarfaceIbit (avoids costant recompilation)
Also this is the last time i tried to fix it but i didn't know the correct addresses.
https://youtu.be/FokFdYV5Pgc
I hope in an your answer soon.

**Comment by kozarovv** [comment]
Thanks, I'm aware about this pcsx2 fix since 2016 year ;) Anyway this have no use for PS4 emulator, until you find someone who can rewrite that to LUA used in emulator. This way will be even better. About flickering, please post video with issue. Maybe i can help little bit.

**Comment by Vitt0xLar** [comment]
> Thanks, I'm aware about this pcsx2 fix since 2016 year ;) Anyway this have no use for PS4 emulator, until you find someone who can rewrite that to LUA used in emulator. This way will be even better. About flickering, please post video with issue. Maybe i can help little bit.


Ok for the flickering/disappearing textures here's a video on youtube (not my chanell) : 
https://youtu.be/sQippT4kPpo?t=25

i've tried gs mipmapping and everything about that but nothing
The Rom type is EUROPE PAL VERSION.
Also another thing if i precompile from  0x7fffffff to 0x80000000, will this fix the costant recompilation code? I'm just curious to know it.

**Comment by paindubreak** [comment]
So, any news of fix for scarface ps3 ?

**Comment by Fayt420** [comment]
I would love to figure this out.

**Comment by uakhan1** [comment]
Yes, highly likely fix can be made. As everything in scarface works on ps3 slim except framrate. If there is a fix, alot of people will be happy
